### ISSUE TITLE
resolver="2" breaks support for Rust 1.48.0

### ISSUE THREAD

**Issue by link2xt** [dignifiedquire/async-tar#28]
Fix #22 introduced `resolver="2"` option in `Cargo.toml`.

Even though MSRV is 1.51, it would be nice to avoid this as for deltachat-core-rust MSRV is 1.48.0 and updating async-tar breaks CI.

**Comment by link2xt** [comment]
If it's difficult, maybe we should discuss bumping MSRV to 1.51 for deltachat-core-rust.

There is another dependency, zeroize_derive, which is used by pgp and crypto code, which also broke rust 1.48.0 compatibility recently: https://github.com/iqlusioninc/crates/pull/755

But even Debian sid still has rustc 1.50.0

**Comment by dignifiedquire** [comment]
@link2xt deltachat-core-rust will need to switch to a newer rust with the next rpgp release as well. All new crypto release have an MSRV of 1.51 and it will likely not be too long until even newer, due to the const improvements.
