### ISSUE TITLE
Switch to smaller runtime

### ISSUE THREAD

**Issue by oblique** [dignifiedquire/async-tar#8]
I'm thinking to open a PR that will migrate from async-std to async-fs/futures-io. I believe this will make async-tar more attractive to people that do not use async-std.

If I do this, are you willing to accept it?

**Comment by silverjam** [comment]
I would be in favor of this, we have a tokio based application (using warp) -- so not having to bring in async-std would be a good thing.

**Comment by danieleades** [comment]
agree with the above. I think possibly disabling the runtime in async-std might be an ok halfway-house too (`default-features = false`)
